services:
  frontend:
    build:
      context: ./src/frontend/my-app
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    restart: unless-stopped